#!/usr/bin/env zsh
#
# chinstrap build tool
# deps: jq, bash, curl, gpg, pacman, mkarchroot, makechrootpkg

# load modules
zmodload zsh/zutil
zmodload zsh/mapfile
autoload colors; colors

# load config file
() {
  for rc in $(pwd)/.chinstraprc $HOME/.config/chinstraprc /etc/chinstraprc
  do; [[ -f $rc ]] && { source $rc && break }; done
}

# setup environment
declare -g working_dir=${working_dir:=$(pwd)}
declare -g chroot_dir=${chroot_dir:="$working_dir/build_root/"}
declare -g pacman_conf=${pacman_conf:="$working_dir/configs/pacman.conf"}
declare -g makepkg_conf=${makepkg_conf:="$working_dir/configs/makepkg.conf"}
declare -g aur_url=${aur_url:="https://aur.archlinux.org"}
declare -g aur_rpc=${aur_rpc:="$aur_url/rpc?v=5&"}
declare -g gpg_key=${gpg_key:="1234567890ABCDEF"}
declare -g push_login=${push_login:="user@host.domain.url"}
declare -g push_path=${push_path:="/srv/http/repo/custom/x86_64"}
declare -g push_auto=${push_auto:-false}

# config() - setup chinstrap
function config () {
  [[ -n $@ ]] || { usage; return 1 }

  zparseopts -D -E -F - \
    C=mode -chroot=mode \
    U=mode -update=mode \
    d:=w_dir -dir:=w_dir \
    m:=makepkg -makepkg:=makepkg \
    p:=pacman -pacman:=pacman \
    || return 1

  local end_opts=$@[(i)(--|-)]
  set -- "${@[0,end_opts-1]}" "${@[end_opts+1,-1]}"
  test -z $@ || { usage; return 1 }

  [[ -n $w_dir ]] && chroot_dir=$w_dir[2]
  [[ -f $makepkg[2] ]] && makepkg_conf=$makepkg[2]
  [[ -f $pacman[2] ]] && pacman_conf=$pacman[2]

  case $mode in 
    -C | --chroot ) create_chroot ;;
    -U | --update ) update_chroot ;;
    * ) echo "Invalid mode: $mode"; exit 1 ;;
  esac
}

function create_chroot () {
  if [[ -d $chroot_dir ]]; then
    echo_wrn "Path exists: $chroot_dir"
  else
    echo_inf "Creating base directory: $chroot_dir"
    mkdir -p $chroot_dir > /dev/null 2>&1 \
      || sudo mkdir -p $chroot_dir
  fi

  if [[ -d $chroot_dir/root ]]; then
    echo_err "Existing chroot environment detected"
    exit 1
  else
    echo_inf "Creating chroot environment: $chroot_dir"
    mkarchroot \
      -M $makepkg_conf \
      -C $pacman_conf \
      $chroot_dir/root base-devel \
      || exit 2
  fi
}

# update_chroot() - update packages of chroot environment
function update_chroot () {
  [[ -d $chroot_dir ]] \
    || { echo_err "Invalid chroot_dir: $chroot_dir"; exit 1 }

  echo_msg "Updating chroot environment..."
  arch-nspawn \
    -M $makepkg_conf \
    -C $pacman_conf \
    $chroot_dir/root pacman -Syu --noconfirm \
    || { echo_err "Failed to update chroot: $chroot_dir"; exit 2 }
}

# list() - list packages in $working_dir
function list () {
  zparseopts -D -E -F - \
    g=filter -git=filter \
    a=filter -aur=filter \
    b=filter -built=filter \
    d:=dir -dir:=dir \
    || return 1

  local end_opts=$@[(i)(--|-)]
  set -- "${@[0,end_opts-1]}" "${@[end_opts+1,-1]}"
  test -z $@ || { usage; return 1 }

  [[ -n $dir && -d $dir[2] ]] && working_dir=$dir[2]

  echo_msg "Listing packages in $working_dir..."
  cd $working_dir || return 1

  local -a packages
  local -a filtered

  for item in *; do
    [[ -d $item ]] || continue
    cd $item || return 1
    is_package \
      && packages=($packages $item)
    cd $working_dir || return 1
  done

  if [[ -n $filter ]]; then
    echo_inf "Filter: $filter"
    for package in $packages; do
      cd $package || return 1
      case $filter in
        -a | --aur)
          is_aur $package \
            && filtered=($filtered $package)
          ;;
        -b | --built)
          is_built \
            && filtered=($filtered $package)
          ;;
        -g | --git)
          is_git \
            && filtered=($filtered $package)
          ;;
      esac
      cd $working_dir || return 1
    done
    packages=($filtered)
  fi

  for pkg in $packages; do
    cd $pkg || return 1
    local info=($(get_pkg_info))
    echo_itm "${fg_bold[white]}$info[1]" \
      "${fg[green]}$info[2]-$info[3]${reset_color}"
    cd $working_dir || return 1
  done
}

# get_pkg_info() - print PKGBUILD name version and release
get_pkg_info () {
  bash -c 'source PKGBUILD; echo $pkgname $pkgver $pkgrel' \
    || return 1
}

# is_package() - check if path contains PKGBUILD
function is_package () {
  [[ -f PKGBUILD ]] || return 1
}

# is_aur() - check if pkg is in AUR
function is_aur () {
  [[ $(curl -s "$aur_rpc&type=info&arg=$1" | jq -r '.resultcount') == 1 ]] \
    || return 1
}

# is_built() - check if path contains built package
function is_built () {
  for file in $(makepkg --packagelist); do
    [[ -f $file ]] || return 1
  done
}

# is_git() - check if path is git repo
function is_git () {
  [[ -d .git ]] || return 1
}

# fetch() - fetch PKGBUILD(s)
function fetch () {
  [[ -n $@ ]] || { usage; return 1 }
  zparseopts -D -E -F - l:=list -list:=list || return 1
  local end_opts=$@[(i)(--|-)]
  set -- "${@[0,end_opts-1]}" "${@[end_opts+1,-1]}"
  
  local -aU packages=($@)
  local pkg_list=$list[-1]

  if [[ -f $pkg_list ]]; then
    for line in ${(f)mapfile[$pkg_list]}; do
      read first _ <<< $line
      [[ ! $first == '#'* ]] && packages=($packages $first)
    done
  fi
  
  echo_msg "Fetching PKGBUILD(s)..."
  cd $working_dir || return 1

  for package in $packages; do
    if is_aur $package; then
      if [[ ! -d $package ]]; then
        clone_pkg $package \
          || echo_err "$package sync failed"
      else
        echo_wrn "$package exists"
      fi
    else
      echo_wrn "$package unavailable"
    fi
  done
}

# clone package
function clone_pkg () {
  git clone --quiet $aur_url/$1 \
    && echo_bul "Cloned $1"
}

# build() - build PKGBUILD(s)
function build () {
  [[ -n $@ ]] || { usage; return 1 }
  zparseopts -D -E -F - l:=list -list:=list || return 1

  local end_opts=$@[(i)(--|-)]
  set -- "${@[0,end_opts-1]}" "${@[end_opts+1,-1]}"
  
  local -aU packages=($@)
  local pkg_list=$list[-1]

  if [[ -f $pkg_list ]]; then
    for line in ${(f)mapfile[$pkg_list]}; do
      read first _ <<< "$line"
      [[ ! $first == '#'* ]] \
        && packages=($packages $first)
    done
  fi

  cd $working_dir || return 1

  for package in $packages; do
    cd $package || return 1
    if is_package; then
      echo_inf "Building $package..."
      update_chroot
      prepare_git
      prepare_checksums
      prepare_srcinfo
      build_pkg
      sign_pkg
      [[ $push_auto = true ]] \
        && upload_pkg
    else
      echo_err "$package not found!"
    fi
    cd $working_dir || return 1
  done
}

# prepare_git() - pull latest version of PKGBUILD
function prepare_git () {
  is_git || return 1
  echo_bul "Updating PKGBUILD..."
  git pull --quiet \
    || { echo_err "Failed to update PKGBUILD"; return 2 }
}

# prepare_checksums() - update source checksums
function prepare_checksums () {
  echo_bul "Updating checksums..."
  updpkgsums \
    || { echo_err "Failed to update checksums"; return 2 }
}

# prepare_srcinfo() - update .SRCINFO file
function prepare_srcinfo () {
  echo_bul "Updating .SRCINFO..."
  makepkg --printsrcinfo >! .SRCINFO \
    || { echo_err "Failed to update .SRCINFO"; return 2 }
}

# build_pkg() - build individual package
function build_pkg () {
  local info=($(get_pkg_info))
  echo_inf "Building $info[1] $info[2]-$info[3]..."
  makechrootpkg -c -r $chroot_dir \
    || return 2
}

# sign_pkg() - crate detached sig for pkg
function sign_pkg () {
  local packages=($(makepkg --packagelist))
  for package in $packages; do
    gpg --detach-sign --quiet $package \
      || { echo_err "Failed to sign package: $package"; return 2 }
  done
}

# push() - push package(s)
function push () {
  [[ -n $@ ]] || { usage; exit 1 }
  zparseopts -D -E -F - \
    l:=list -list:=list \
    h:=host -host:=host \
    d:=dir -dir:=dir \
    || return 1

  local end_opts=$@[(i)(--|-)]
  set -- "${@[0,end_opts-1]}" "${@[end_opts+1,-1]}"
  
  [[ -n $host ]] && push_login=$host[2]
  [[ -n $dir ]] && push_path=$dir[2]

  local -aU packages=($@)
  local pkg_list=$list[-1]

  if [[ -f $pkg_list ]]; then
    for line in ${(f)mapfile[$pkg_list]}; do
      read first _ <<< "$line"
      [[ ! $first == '#'* ]] && packages=($packages $first)
    done
  fi

  cd $working_dir || return 1

  for package in $packages; do
    cd $package || return 1
    is_built && upload_pkg \
      || echo_err "$package not found!"
    cd $working_dir || return 1
  done
  unset pkg
}

# upload_pkg() - upload package(s) to repo
function upload_pkg () {
  for pkg in $(makepkg --packagelist); do
    echo_msg "Pushing $(pwd) to remote..."
    rsync -av $pkg $pkg.sig $push_login:$push_path \
      || { echo_err "Failed to sync: $pkg" }
  done
}

# print colorized output
function echo_msg () { echo "${fg_bold[blue]}:: ${fg_bold[white]}${@}${reset_color}" }
function echo_bul () { echo "${fg_bold[blue]}  -> ${fg_bold[white]}${@}${reset_color}" }
function echo_itm () { echo "${@}" }
function echo_inf () { echo "${fg_bold[green]}==> ${fg_bold[white]}${@}${reset_color}" }
function echo_wrn () { echo "${fg_bold[yellow]}==> WARNING: ${fg_bold[white]}${@}${reset_color}" }
function echo_err () { echo "${fg_bold[red]}==> ERROR: ${fg_bold[white]}${@}${reset_color}" }

# help
function usage() {
  echo "Usage: ${ZSH_ARGZERO:t} <mode> [<pkg>] [--list <file>]"
  echo
  echo "  fetch <pkg(s)>          Fetch package(s) from AUR"
  echo "    -l, --list <file>     List of packages to work on"
  echo  
  echo "  build <pkg(s)>          Build package(s)"
  echo "    -l, --list <file>     List of packages to work on"
  echo
  echo "  push  <pkg(s)>          Push package(s) to repo"
  echo "    -l, --list <file>     List of packages to work on"
  echo "    -h, --host <host>     Login for remote host"
  echo "    -d, --dir <dir>       Path on remote host"
  echo  
  echo "  list                    List available packages"
  echo "    -a, --aur             Filter AUR packages (slow)"
  echo "    -b, --built           Filter built packages (really slow)"
  echo "    -g, --git             Filter git packages"
  echo  
  echo "  config                  Manage chroot"
  echo "    -C, --chroot          Create chroot environment"
  echo "    -U, --update          Manualy update chroot"
  echo "    -d, --dir             Location of \$chroot_dir"
  echo "    -m, --makepkg         Location of makepkg config (use with -C)"
  echo "    -p, --pacman          Location of pacman config (use with -C)"
  echo
}

## main()
function main ()
{
  local mode=${@[1]}
  local args=(${@[2,-1]})

  case $mode in
    fetch | build | list | push | config ) $mode $args ;;
    -h | --help | ? | * ) usage ;;
  esac
}

main $@
